### ISSUE TITLE
What is the performance gain?

### ISSUE THREAD

**Issue by bit-scientist** [cyrusbehr/YOLOv8-TensorRT-CPP#1]
Hello, @cyrusbehr, I can see that you provide tensorRT model for C++ inference. Currently, I am using tensorRT's .engine model exported for python API and it's working around 60% faster (in object tracking) compared to pytorch's .pt model. I wonder if I can make it more faster (with little or no accuracy drop) with your solution. Do you have any estimates on this, like how much faster it gets and what % accuracy is lost (specific to your GPU model)? Thank you a lot!

**Comment by cyrusbehr** [comment]
The accuracy should be the same since you are using the same underlying inference engine (TensorRT in both cases). You can get more performance if you switch to using FP16 inference instead of FP32 inference.

If you provide me with the Python TensorRT inference code, I can run benchmarks on my end and compare those with C++ implementation to provide you with a comparison.

**Comment by bit-scientist** [comment]
@cyrusbehr Thank you, I now understand. I benchmarked .pt, .onnx and .engine models with yolov8's tracking and got faster performance on .engine. I wrote a simple code to compare:
```
from ultralytics import YOLO
import time

models = {
    'pt model': 'custom.pt',
    'onnx model': 'custom.onnx',
    'engine model': 'custom.engine'
}
times = 100

execution_times = {}
average_times = {}

for model_description, model_name in models.items():
    model = YOLO(model_name)
    execution_times[model_description] = []
    total_time = 0

    # print(f"{model_description}:")
    for run in range(1, times + 1):
        start_time = time.time()
        results = model.track(line_thickness=1, source="F:/v8/ultralytics/assets/video.mp4",show=True, imgsz=(736, 1280), verbose=False)
        execution_time = time.time() - start_time
        execution_times[model_description].append(execution_time)
        total_time += execution_time

    average_time = total_time / times
    average_times[model_description] = average_time

print("Execution:")
header = "{:<20}".format("Model")
for model_description in models.keys():
    header += "{:<20}".format(model_description)
print(header)

max_runs = max(len(times) for times in execution_times.values())

for run in range(max_runs):
    row = "{:<20}".format(f"Run {run+1}:")
    for model_description in models.keys():
        exec_time = execution_times[model_description][run]
        row += "{:<20.3f}".format(exec_time)
    print(row)

avg_row = "{:<20}".format("Avg time")
for model_description in models.keys():
    avg_time = average_times[model_description]
    avg_row += "{:<20.3f}".format(avg_time)
print(avg_row)
```

Not sure if it'd be useful but still.

**Comment by cyrusbehr** [comment]
Great thank you for sharing the script.

**Comment by pva22** [comment]
@cyrusbehr Hi, thank you very much for this project! I'm trying to evaluate the performance. Could not get to the pointers that were introduced in this article - https://www.stereolabs.com/blog/performance-of-yolo-v5-v7-and-v8 /.  I want to share my performance indicators. It was possible to access Ubuntu 18.04 and on Tesla T4, A2, A100 cards (when building OpenCV, it is impossible to load CUDA_ARCH_BIN for the console card - https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards /). 

```
On Tesla A2: 
  model yolov8n: 
    1280x720- 138 FPS;
    640x480 - 168 FPS;
  model yolov8x: 
    1280x720 - 35 FPS;
    640x480 - 36 FPS.  

On Tesla A100, yolov8n: 
  640x480 - 248 FPS;
  1280x720 - 230 FPS.

On Tesla T4: 
  1280x720 - 196 FPS. 
```
  
Please share your performance results. Do you have any ideas how colleagues managed to achieve 1000+ FPS?

**Comment by cyrusbehr** [comment]
Thanks for sharing the benchmarks. I imagine those numbers were attained with the use of batching. Even then, a 5X speed up would be required to achieve 1000 FPS. I’ll need to run some benchmarks on my end and get back to you.

**Comment by bit-scientist** [comment]
> If you provide me with the Python TensorRT inference code, I can run benchmarks on my end and compare those with C++ implementation to provide you with a comparison.

May I expect any news on this, @cyrusbehr ?

**Comment by cyrusbehr** [comment]
@pva22 I pushed a change which cuts down on some of the preprocessing time (ex. Benchmark using an image which is already 640x640, RGB, and in GPU memory), so that cuts the time down a bit. Even then, I'm having a hard time seeing how they achieved 1000+FPS

On my `3050 Ti Laptop GPU` and i9 11th gen, using yolo8n
```
======================
Avg time: 
3.825ms

Avg FPS: 
261 fps
======================
```

I've created a branch `timing` which you are welcome to checkout. It breaks down the timing:
ex. 
```
Preprocess time: 144us
Inference: 2581us
Postprocess time: 959us
```

Seems quite a lot of time is being taken up by post-processing. The post processing (bbox decoding and NMS) is done entirely in CPU memory. I probably need to do it in GPU memory using cuda kernels to speed things up.

**Comment by cyrusbehr** [comment]
@bit-scientist 
I tried your provided script, and also tried writing my own, but in the end, I decided to just use the command that Ultralytics used for their benchmakrs: 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/de89acfe-08ba-4921-b559-40961f8b9551)
I use the yolov8n model.

On my `3050 Ti Laptop GPU` the results are `Speed: 0.7ms preprocess, 6.4ms inference, 0.0ms loss, 0.5ms postprocess per image` which is a total of `7.6` ms. You can compare that to my results breakdown above.

**Comment by cyrusbehr** [comment]
On my `RTX 4090` and `Intel(R) Xeon(R) W-3323 CPU @ 3.50GHz`, my implementation: 
```
Benchmarking complete!
======================
Avg time: 
3.6974ms

Avg FPS: 
270 fps
======================
```

With a sample breakdown of times:
```
Preprocess time: 151us
Inference: 1372us
Postprocess time: 2015us
```

So the post processing is definitely the bottle neck. I need to work on that. 

Running `yolo val detect data=coco128.yaml batch=1 device=0` yields the following:
```
Speed: 0.3ms preprocess, 7.6ms inference, 0.0ms loss, 0.8ms postprocess per image
```

**Comment by cyrusbehr** [comment]
You can check out the Benchmarking section [here](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP#benchmarking)

**Comment by bit-scientist** [comment]
@cyrusbehr appreciate your efforts, thanks.

**Comment by cyrusbehr** [comment]
If you want a faster implementation, check [this](https://github.com/wang-xinyu/tensorrtx/tree/master/yolov8) one out. It's faster than the one I've written. It's also much more complex though, it involves using the TensorRT API to build the graph from scratch.
