### ISSUE TITLE
Build on Windows

### ISSUE THREAD

**Issue by ap-apely** [cyrusbehr/YOLOv8-TensorRT-CPP#14]
Is it possible to build it on Windows. I am trying to redact cmakelists.txt, findtensorrt.cmake. But I didn't get the make file. And one more question, can i use it in my projects?### 
My tech specs:
- Windows 10 x64
- Cuda 11.8
- CudaNN 8.9.1
- Tensorrt 8.5.3.1

**Comment by cyrusbehr** [comment]
Sorry I won't be providing support or instructions for building on Windows as I only used unix platforms myself. 
If you get it working on Window's, you're welcome to open a PR with the modifications which are requires.

Yes you can use it in your project, license is MIT.

**Comment by Lishumuzixin** [comment]
> Is it possible to build it on Windows. I am trying to redact cmakelists.txt, findtensorrt.cmake. But I didn't get the make file. And one more question, can i use it in my projects?### My tech specs:
> 
> * Windows 10 x64
> * Cuda 11.8
> * CudaNN 8.9.1
> * Tensorrt 8.5.3.1

Hello,did you built it on windows?What needs to change to adapt to windows?

**Comment by cyrusbehr** [comment]
Hi, please check out [this fork](https://github.com/xunzixunzi/YOLOv8-TensorRT-CPP/tree/main) which demonstrates how to build for windows.
