### ISSUE TITLE
Cmake can’t find TensorRT 

### ISSUE THREAD

**Issue by Nimaro76** [cyrusbehr/YOLOv8-TensorRT-CPP#16]
Hello,
Thank you for sharing this repository. After installing the requirements, I cloned it and built it . However, I received this error:
  Could NOT find TensorRT (missing: TensorRT_LIBRARY) (found version "..")
Call Stack (most recent call first):
  /home/safebot/.local/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindTensorRT.cmake:73 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libs/tensorrt-cpp-api/CMakeLists.txt:22 (find_package)
 
 
Which is strange considering I used Debian to install TensorRT and the library gets installed by default on 
set(TensorRT_DIR /usr/lib/x86_64-linux-gnu/)
And I checked that as well.  I also used cmake gui to build it and I got this error after specifying /usr/lib/x86_64-linux-gnu as library directory :TensorRT_NVONNXPARSER_LIBRARY-NOTFOUND

I would appreciate it if you could help me identify the source of this issue when building the project.
Kind regards
 Nima

**Comment by Nimaro76** [comment]
Issue solved. Thank you

**Comment by cyrusbehr** [comment]
Can you please explain how you solved the issue so that if others have the same issue they know what to do.

**Comment by Nimaro76** [comment]
Yes sure. Basically, the problem is the Debian installation of tensor RT. The problem will be solved simply by installing with the tar file of tensor RT not using Debian installation. Cmake can’t find tensorRT in Debian default path .
