### ISSUE TITLE
No objects detected, with no errors

### ISSUE THREAD

**Issue by JPhiDev** [cyrusbehr/YOLOv8-TensorRT-CPP#17]
Thank you in advance for your time and work. I am currently trying to use the YOLOv8 output into a ROS1 environment, as ROS1 needs C++.

Running Ubuntu 20 on a Jetson Orin Nano.

Following your instructions:
Everything installed successfully, and I am currently not receiving any errors. 

I converted the yolov8n.pt to onnx.
When I run inference on a test image, or open my webcam I do not see any annotated results and no errors produced. Not sure where to go from here... lol? I saw the other issue/question. I do not have another Cuda enabled PC to test on. I do run other normal YOLOv8 packages not using your repository, successfully.
![results](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/78062088/f5949ad0-87ac-41f9-a886-9f6a5fed3bca)

**Comment by cyrusbehr** [comment]
Hmm, that is strange. Let me give it some thought on what the issue might be.

**Comment by JPhiDev** [comment]
No problem. Thank you for the quick response. I've been at it for several hours now, and I haven't found a solution. If you need any more data/input from me just let me know.

**Comment by JPhiDev** [comment]
So, I tried to rebuild the "engine" file to rule this out. This could be the problem.
I received the following error when using "./detect_object_image" on one of the test images. 

I performed the instructions you listed for converting to INT8 along with the calibration data.

Would I need to change the batch default params to adjust for this INT8 conversion? I changed severity to "kVERBOSE," but the same errors come up, nothing more.
Thanks.
![result_02](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/78062088/95cb9d92-5fe7-4bfb-992f-6dba25f4c1e9)

**Comment by cyrusbehr** [comment]
Yes, please see this note [here](https://github.com/cyrusbehr/tensorrt-cpp-api#int8-inference):

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/f1053bf8-398f-462f-a004-3054069cabab)

Can you confirm it works with FP16/FP32 inference before moving to INT8 inference.

**Comment by JPhiDev** [comment]
I deleted old "engine" file. Re-ran the script "./detect_object_image --model ../models/yolov8n.onnx --input ../images/cars.jpg"
It generated a new engine file, and the detected objects is still zero, with no annotations on image produced.
![results_03](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/78062088/1e29b791-aed6-4ef7-8859-eb7711ba05f7)

**Comment by alfanrizaldy** [comment]
@JPhiDev 
What yolov8 variant do you use? I've use the nano and small variant that can resulting detected object. But, when i'm use the medium and larger variant, i can't get the detection result
Here is my issues https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/issues/6

@cyrusbehr 
I'm sorry, currently i haven't try in x86 device because didn't have any device to try

**Comment by JPhiDev** [comment]
@alfanrizaldy 
I am using the Orin Nano 8GB Dev with Jetpack 5.1.1.
I tried all versions of the yolov8 models with no success. They all produced "Detected 0 objects."

@cyrusbehr 
This may not matter...
But is OpenCV 4.7 specifically required for any reason? I saw in the comments (pictured below) you specify OpenCV 4.7 is required for NMSBoxesBatched.

I am using OpenCV 4.8 with Cuda support. I assumed OpenCV >= version 4.7 would be okay.
![opencv4 7](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/78062088/b179c33c-b0da-4623-9c88-18df0bb28b9f)

**Comment by cyrusbehr** [comment]
Yeah the OpenCV version should be fine.

**Comment by cyrusbehr** [comment]
If someone can give me ssh access to a Jetson device which is not working, I can try to debug this.

**Comment by JPhiDev** [comment]
@cyrusbehr I apologize for the late response. I was sidetracked to a different project for a bit. I am unable to give SSH access as of now to that Jetson device. If something changes I will let you know. I will continue to work on this when I have a chance to see if I can find the issue and report back when if do. I am back and forth between projects, so it may not be very soon.

**Comment by dsy0007** [comment]
Nice to meet you. I've experienced a similar issue and resolved it. I'd like to share the method I used to solve it.
I also couldn't detect anything at all, just like you mentioned. However, I started to detect objects correctly after changing the 'half' argument from true to false during the YoloV8 model export to onnx format process.

I hope this helps.

**Comment by cyrusbehr** [comment]
@dsy0007 if you used my conversion scripts, then the half parameter should not have been set to true, so I'm not sure if that's the issue the others were experiencing or not.

**Comment by Manueljohnson063** [comment]
I am having the same issue i am using Jetson xavier .No errors but the images with out detection

**Comment by cyrusbehr** [comment]
Hi there, please see the `feat/jetson-tx2` branch. If it still does not work for you, re-open the issue.

**Comment by all-for-code** [comment]
> @dsy0007 if you used my conversion scripts, then the half parameter should not have been set to true, so I'm not sure if that's the issue the others were experiencing or not.

@cyrusbehr @dsy0007 changing the 'half' argument from true to false during the YoloV8 model export to onnx format process works for me. I have checked the official documentation for yolov8 and the half parameter of pytorch model to onnx is false by default
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/110803332/1b9cedc8-d535-4c7f-a6f5-5e69ee87f2a5)
https://docs.ultralytics.com/modes/export/#arguments
