### ISSUE TITLE
Cannot build yolov8n-seg.pt when using INT8

### ISSUE THREAD

**Issue by xunzixunzi** [cyrusbehr/YOLOv8-TensorRT-CPP#19]
Thanks for your creative work. 
I am currently using your project on Windows 10. For detection, it has worked successfully when using FP16 or INT8. For segmentation, it has worked successfully when using FP16.
I tried to build yolov8n-seg.pt in INT8 precision, but some errors occurred.

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/42097809/345eed1e-04ad-4243-896f-c776b970922e)

If you have any problems, I can provide you with more information.

**Comment by KZyred** [comment]
Hello,how did you built it on windows?
What needs to change to adapt to windows?

**Comment by KZyred** [comment]
@xunzixunzi xunzixunzi

**Comment by cyrusbehr** [comment]
Seems that TensorRT may not have added INT8 support for that layer yet.

**Comment by cyrusbehr** [comment]
@KZyred please see this pull request for Windows support: https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/pull/21
