### ISSUE TITLE
Jetson-TX2 contribution

### ISSUE THREAD

**Issue by ltetrel** [cyrusbehr/YOLOv8-TensorRT-CPP#22]
Hi, and thanks for your work.

I updated your code to make it work on a jetson-TX2 which is compatible with:
* OpenCV GSTREAMER
* C++14

https://github.com/ltetrel/YOLOv8-TensorRT-CPP/tree/feat/jetson-tx2

Let me know how you want to proceed, from there I see 3 options:
1. Changes in another branch `feat/jetson-tx2` (as I did on my fork). I recommend this and I would need you to create this branch on your repo so I can make a PR.
2. Changes living in `main` branch. I don't recommend this to avoid polluting your original code but that could be possible to have everything at the same place with a bunch of `#ifdef` depending on cuda version , c++ etc...
3. No mention to this work on your repo, even if I think it could benefit the community.

See also: https://github.com/cyrusbehr/tensorrt-cpp-api/issues/21

Let me know,

**Comment by cyrusbehr** [comment]
Hi @ltetrel 
Thank you for the good work. 

Let's go with your recommended approach. I'll create the `feat/jetson-tx2` branch and you can create a PR with your work. Thank you for your contribution.

**Comment by ltetrel** [comment]
Thanks,
https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/pull/23

**Comment by cyrusbehr** [comment]
https://github.com/all-contributors please add @ltetrel for code

**Comment by cyrusbehr** [comment]
@all-contributors please add @ltetrel for code
