### ISSUE TITLE
Trained the model with imgz parammeter 416

### ISSUE THREAD

**Issue by Manueljohnson063** [cyrusbehr/YOLOv8-TensorRT-CPP#24]
Hi ,
First of all thanks for your great repo
I have worked this repo for my custom segmentation task ,Now for improving my FPS i had reduced the imgz from  640 to 416 .when i have given that .onnx model it shows error in the post processing function.
Can you please help me out.

**_terminate called after throwing an instance of 'std::logic_error'
  what():  Output at index 0 has incorrect length
Aborted (core dumped)_**

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/44712542/e245b9bf-4297-453a-a5ad-e2bd91bfa180)

Input video i am giving is 1920x1080
Board :Jetson Xavier

@cyrusbehr @z3lx

**Comment by cyrusbehr** [comment]
Hi @Manueljohnson063 you'll need to modify these parameters for the model you have trained: https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/blob/eeaaa98cec8dea0166569ac50569019aca94b08e/src/yolov8.h#L38-L40

**Comment by cyrusbehr** [comment]
If you use netron to examine the onnx model, you'll be able to see the expected output size: 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/301d3395-7813-4e35-9a3f-c71310a8aee7)

**Comment by Manueljohnson063** [comment]
Thankzzzz.... a lot sir Now its correct.
I need to know one more thing i needs to run the model with batch parallelisation .When i tried to generate the ONNX  model with dynamic input ,and when i inputted that to run our code ,
i have noticed that it have encountered  error at engine generation.
can you please help me sir
Thanks in advance....

**Comment by Lishumuzixin** [comment]
> Thankzzzz.... a lot sir Now its correct. I need to know one more thing to run the model with batch parallelisation ,When i tried to generate the ONNX model with dynamic input ,and when i inputted that to run our code , i have noticed that it have encountered error at engine generation. @cyrusbehr can you please help me sir Thanks in advance....

 Have you solved your problem? How can the batch of exported yolov8 exported be dynamic, but the height and width are not

**Comment by andrew-93** [comment]
@Lishumuzixin for onnx with dynamic width/height you can modify code, as shown below:
1. Open the file `YOLOv8-TensorRT-CPP/libs/tensorrt-cpp-api/src/engine.cpp ` and find this part of code:
```
    int32_t inputC = inputDims.d[1];
    int32_t inputH = inputDims.d[2];
    int32_t inputW = inputDims.d[3];
```
Change `inputDims.d[2]` and `inputDims.d[3]` to the desired **Input height** and **Input width** values accordingly.

2. Don't forget to change the size of the output tensor in the file **yolov8.h**:
```
    int segChannels = 32;
    int segH = desired_input_height_value / 4;
    int segW = desired_input_width_value / 4;
    float segmentationThreshold = 0.5f;
```
3. rebuild.
