### ISSUE TITLE
How to set "CUDA lazy loading" ??

### ISSUE THREAD

**Issue by YangSangWan** [cyrusbehr/YOLOv8-TensorRT-CPP#33]
I try example!  "object_detection_image"  and get this message

CUDA lazy loading is not enabled. Enabling it can significantly reduce device memory usage and speed up TensorRT initialization. See "Lazy Loading" section of CUDA documentation https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#lazy-loading

How to set "CUDA lazy loading" in example??

**Comment by cyrusbehr** [comment]
It says right there in the docs you linked: 

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/6bc507e0-7d1f-434a-95af-c7eb1c5114cf)

So just set the environment variable in your shell: `export CUDA_MODULE_LOADING=LAZY` or do so programmatically from the code before creating an instance of the TensorRT engine.
