### ISSUE TITLE
Untrusted benchmark test??

### ISSUE THREAD

**Issue by vvxt** [cyrusbehr/YOLOv8-TensorRT-CPP#34]
2000 iterations fast, but 100000 times, very, very slow. why??

2000 iterations Avg time: 4.8025 ms，Avg FPS:208 fps.
100000 iterations More than 5 minutes outputting results, still working...

start...
Avg Preprocess time: 0.42 ms
Avg Inference time: 1.447 ms
Avg Postprocess time: 2.915 ms

Avg Preprocess time: 0.42 ms
Avg Inference time: 1.447 ms
Avg Postprocess time: 2.915 ms

Avg Preprocess time: 0.419 ms
Avg Inference time: 1.447 ms
Avg Postprocess time: 2.914 ms

**... After 1 minute...**

Avg Preprocess time: 1.18 ms
Avg Inference time: 4.677 ms
Avg Postprocess time: 3.895 ms

Avg Preprocess time: 1.18 ms
Avg Inference time: 4.677 ms
Avg Postprocess time: 3.895 ms

Avg Preprocess time: 1.18 ms
Avg Inference time: 4.677 ms
Avg Postprocess time: 3.895 ms

**... After 3 minutes ...**

Avg Preprocess time: 1.245 ms
Avg Inference time: 4.911 ms
Avg Postprocess time: 3.894 ms

Avg Preprocess time: 1.245 ms
Avg Inference time: 4.911 ms
Avg Postprocess time: 3.894 ms

Avg Preprocess time: 1.245 ms
Avg Inference time: 4.911 ms
Avg Postprocess time: 3.894 ms

------------------------------------------------
Why is it getting slower and slower??

**Comment by cyrusbehr** [comment]
Was not able to reproduce
