### ISSUE TITLE
Grey scale image for infrence

### ISSUE THREAD

**Issue by Manueljohnson063** [cyrusbehr/YOLOv8-TensorRT-CPP#35]
Hai,
I have trained grey scale images for a segmentation model .Does  your repo supports the grey scale images thanks in advance.....
@cyrusbehr @z3lx

**Comment by cyrusbehr** [comment]
Yes it works for 1 channel gray scale images. You just need to preprocess the input images to single channel gray scale before calling the `Engine::runInference` method.

**Comment by Manueljohnson063** [comment]
Many many thanks @cyrusbehr
