### ISSUE TITLE
dynamic batch

### ISSUE THREAD

**Issue by Lishumuzixin** [cyrusbehr/YOLOv8-TensorRT-CPP#36]
Hello,if I want to change bacth, do I need to add batch=6 to Model.export (format="onnx", simplify=True) when exporting the model?But there is a bug that 'Implementation currently only supports dynamic batch sizes or a fixed batch size of 1.How can I fix it ?

**Comment by Manueljohnson063** [comment]
I have the same issue

**Comment by Anthony1011** [comment]
Hi, I modified the code as follows:
model.export(format="onnx", simplify=True, dynamic=True, batch=2)

I used pytorch2onnx.py to successfully generate an onnx file of shape(2,3,640,640).
The following prompt appears:

> PyTorch: starting from '../models/yolov8x.pt' with input shape (2, 3, 640, 640) BCHW and output shape(s) (2, 84, 8400) (130.5 MB)
> ...

The input shape of the display conversion is (2.3.640.640)
Indicates that two images can be input at the same time and also can be compiled successfully.

But I encountered a problem, I used this command:
./detect_object_image --model ~/yolov8tst/YOLOv8-TensorRT-CPP/models/yolov8x.onnx --input ~/yolov8tst/YOLOv8-TensorRT-CPP/images/horses.jpg
And it is show unable to create engine file successfully,
The error message is:

![Screenshot from 2024-01-08 19-22-32](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/95856492/4179cdee-d425-461e-831d-60606fab5266)

I have two questions:
1. How to successfully solve the problem of being unable to generate engine files?
2. How to input two photos at the same time in the ./detect_object_image command?

**Comment by Anthony1011** [comment]
I find a solution to generate a engine file.
if I setting model.export as below:
model.export(format="onnx", simplify=True, batch=2)
Original we will get a prompt as "what():  Implementation currently only supports dynamic batch sizes or a fixed batch size of 1 (your batch size is fixed to 2)", so I uesd another command is :

> /usr/src/tensorrt/bin/trtexec --onnx=yolov8x.onnx --fp16 --saveEngine=yolov8.trt

Then it can generate a .trt file, after that change the .trt file name as "yolov8x.engine.Orin.fp16.1.1"(according your device) to fit model requirement.

Useing this engine file could run this command:

> ./detect_object_image --model /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/models/yolov8x.onnx --input /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars.jpg

it will show prompt as blow but still detecte successfully.

> Searching for engine file with name: yolov8x.engine.Orin.fp16.1.1
> Engine found, not regenerating...
> 3: [executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.
> )
> Detected 27 objects
> Saved annotated image to: /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars_annotated.jpg

We still have problem wtih input two images at once.

**Comment by Lishumuzixin** [comment]
> @Lishumuzixin I find a solution to generate a engine file. if I setting model.export as below: model.export(format="onnx", simplify=True, batch=2) Original we will get a prompt as "what(): Implementation currently only supports dynamic batch sizes or a fixed batch size of 1 (your batch size is fixed to 2)", so I used another command is :
> 
> > /usr/src/tensorrt/bin/trtexec --onnx=yolov8x.onnx --fp16 --saveEngine=yolov8.trt
> 
> Then it can generate a .trt file, after that change the .trt file name as "yolov8x.engine.Orin.fp16.1.1"(according your device) to fit model requirement.
> 
> Using this engine file could run this command:
> 
> > ./detect_object_image --model /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/models/yolov8x.onnx --input /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars.jpg
> 
> it will show prompt as blow but still detect successfully.
> 
> > Searching for engine file with name: yolov8x.engine.Orin.fp16.1.1
> > Engine found, not regenerating...
> > 3: [executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.
> > )
> > Detected 27 objects
> > Saved annotated image to: /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars_annotated.jpg
> 
> We still have problem with input two images at once.

Is the engine you generated batch=2?

**Comment by Lishumuzixin** [comment]
> > @Lishumuzixin I find a solution to generate a engine file. if I setting model.export as below: model.export(format="onnx", simplify=True, batch=2) Original we will get a prompt as "what(): Implementation currently only supports dynamic batch sizes or a fixed batch size of 1 (your batch size is fixed to 2)", so I used another command is :
> > > /usr/src/tensorrt/bin/trtexec --onnx=yolov8x.onnx --fp16 --saveEngine=yolov8.trt
> > 
> > 
> > Then it can generate a .trt file, after that change the .trt file name as "yolov8x.engine.Orin.fp16.1.1"(according your device) to fit model requirement.
> > Using this engine file could run this command:
> > > ./detect_object_image --model /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/models/yolov8x.onnx --input /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars.jpg
> > 
> > 
> > it will show prompt as blow but still detect successfully.
> > > Searching for engine file with name: yolov8x.engine.Orin.fp16.1.1
> > > Engine found, not regenerating...
> > > 3: [executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.
> > > )
> > > Detected 27 objects
> > > Saved annotated image to: /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars_annotated.jpg
> > 
> > 
> > We still have problem with input two images at once.
> 
> Is the engine you generated batch=2?

我用batch数据成功了，主要是修改preprocess里的inputs，具体的卸载这个博客里了，不多貌似用在我的场景上，这个推断和python的推断还是有点差距的。https://blog.csdn.net/qq_44011202/article/details/135341216?spm=1001.2014.3001.5501

**Comment by Lishumuzixin** [comment]
> @Lishumuzixin I find a solution to generate a engine file. if I setting model.export as below: model.export(format="onnx", simplify=True, batch=2) Original we will get a prompt as "what(): Implementation currently only supports dynamic batch sizes or a fixed batch size of 1 (your batch size is fixed to 2)", so I used another command is :
> 
> > /usr/src/tensorrt/bin/trtexec --onnx=yolov8x.onnx --fp16 --saveEngine=yolov8.trt
> 
> Then it can generate a .trt file, after that change the .trt file name as "yolov8x.engine.Orin.fp16.1.1"(according your device) to fit model requirement.
> 
> Using this engine file could run this command:
> 
> > ./detect_object_image --model /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/models/yolov8x.onnx --input /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars.jpg
> 
> it will show prompt as blow but still detect successfully.
> 
> > Searching for engine file with name: yolov8x.engine.Orin.fp16.1.1
> > Engine found, not regenerating...
> > 3: [executionContext.cpp::setInputShape::2013] Error Code 3: API Usage Error (Parameter check failed at: runtime/api/executionContext.cpp::setInputShape::2013, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape.
> > )
> > Detected 27 objects
> > Saved annotated image to: /home/ubuntu/yolov8tst/YOLOv8-TensorRT-CPP/images/cars_annotated.jpg
> 
> We still have problem with input two images at once.

我用batch数据成功了，主要是修改preprocess里的inputs，具体的写在这个博客里了，不多貌似用在我的场景上，这个推断和python的推断还是有点差距的。https://blog.csdn.net/qq_44011202/article/details/135341216?spm=1001.2014.3001.5501

**Comment by Anthony1011** [comment]
@Lishumuzixin 非常謝謝你的回答，我與我的夥伴正參考你的博客撰寫中，
我預計將改成batch=2，預計一次輸入兩個video streaming進行Object detection，
還在努力修改程式碼中，謝謝你提供的回覆。

**Comment by cyrusbehr** [comment]
Hi folks.
I've updated my tensorrt-cpp-api library to support fixed batch sizes > 1 (v4.1). 

That being said, you will still need to make the modifications to the `yolov8.cpp` code file to pass multiple inference samples to the `Engine::runInfernece` method. I will not be modifying the yolov8.cpp code.
