### ISSUE TITLE
is it detectObject thread safe?

### ISSUE THREAD

**Issue by Xavier1994** [cyrusbehr/YOLOv8-TensorRT-CPP#4]
I want to know whether detectObject is thread safe, that means i can call this function in multi threads

**Comment by cyrusbehr** [comment]
Hi @Xavier1994 
`YoloV8::detectObjects` is not threadsafe. The reason for this is that under the hood, it relies on my [tensorrt-cpp-api](https://github.com/cyrusbehr/tensorrt-cpp-api) project for inference. In that project, the input & output buffers are written to member variable `m_buffers`, defined [here](https://github.com/cyrusbehr/tensorrt-cpp-api/blob/9d1d22208dc2fdb655e2f73c3dd52b76c2a634e9/src/engine.h#L65). To make it threadsafe, you would need to add appropriate synchronization primitives (mutex) or you could ditch the member variable approach and allocate the buffers on every call to `Engine::runInference`.
