### ISSUE TITLE
Custom trained model support

### ISSUE THREAD

**Issue by junho2000** [cyrusbehr/YOLOv8-TensorRT-CPP#40]
Hi thank you for sharing your great work!

i am just curious that can i run executables with my custom trained model?
my model has 12 class, not like coco dataset.

i export my best(yolov8n).pt model to onnx and then i run the detect_object_video 
then output is x,y, width, height are all 0 but only there is class name.

except for this everything works well!

**Comment by eeuwevandijk** [comment]
Which version of OpenCV (C++) do you use? I had several issues with Yolo C++ and ended up with a specific version of OpenCV: v4.7.0 (OpenCV v4.8+ did not work on my system: Jetson Orin AGX)

**Comment by junho2000** [comment]
I am working on my laptop 4060 mobile ubuntu20.04, i installed OpenCV 4.8.0

**Comment by cyrusbehr** [comment]
Please send the model @eeuwevandijk

**Comment by junho2000** [comment]
https://drive.google.com/file/d/13fV2zgIZAsq6ubgGY1CbQld6RmQIe3s_/view?usp=sharing this is my model(best.pt)

**Comment by cyrusbehr** [comment]
@junho2000 

Your model does not have 12 classes like you mention, it has 9 classes:

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/608ef8d1-e962-4105-9dc2-f8b21ce82b00)

That being said, my code does not read the classes automatically from the model. You need to manually specify them. You have two options. 

1) Specify the classes using the `--class-names` command line argument. So it would look like this: `./detect_object_image --model ./best.onnx --input ~/Desktop/sign.png --class-names crosswalk-sign highway-enterance-sign highway-exit-sign no-entry-road-sign one-way-road-sign parking-sign priority-sign round-about-sign stop-sign`
2) Modify the class names in the code. You need to make the change [here](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/blob/afe5a445a64869fb0c5f690ce0d58dc7ea625a41/src/yolov8.h#L47-L55). Replace what's there with your 9 classes. 

Once you make the change, the model works fine. Here is a sample output with your model:


![sign_annotated](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/25b9313f-2044-41fc-a63a-12a100120262)

**Comment by junho2000** [comment]
> @junho2000 
> 
> 
> 
> Your model does not have 12 classes like you mention, it has 9 classes:
> 
> 
> 
> ![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/608ef8d1-e962-4105-9dc2-f8b21ce82b00)
> 
> 
> 
> That being said, my code does not read the classes automatically from the model. You need to manually specify them. You have two options. 
> 
> 
> 
> 1) Specify the classes using the `--class-names` command line argument. So it would look like this: `./detect_object_image --model ./best.onnx --input ~/Desktop/sign.png --class-names crosswalk-sign highway-enterance-sign highway-exit-sign no-entry-road-sign one-way-road-sign parking-sign priority-sign round-about-sign stop-sign`
> 
> 2) Modify the class names in the code. You need to make the change [here](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/blob/afe5a445a64869fb0c5f690ce0d58dc7ea625a41/src/yolov8.h#L47-L55). Replace what's there with your 9 classes. 
> 
> 
> 
> Once you make the change, the model works fine. Here is a sample output with your model:
> 
> 
> 
> 
> 
> ![sign_annotated](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/25b9313f-2044-41fc-a63a-12a100120262)
> 
> 

Thank you so much..!

**Comment by junho2000** [comment]
Hi i tried both method (specify class name at CLI and revise yolov8.h class name) but still nothing detected, same happen

have you did extra thing to work fine?

**Comment by cyrusbehr** [comment]
What platform are you using? If you are running on a jetson, please check out the jetson branch.

**Comment by junho2000** [comment]
i am using on my laptop with geforce 4060 mobile
