### ISSUE TITLE
How to export custom trained engine file

### ISSUE THREAD

**Issue by IamShubhamGupto** [cyrusbehr/YOLOv8-TensorRT-CPP#45]
Hello

I have a custom trained pt file of yolov8 and when I create an engine file using your codebase, it defaults to the coco dataset classes. How do I export and run an engine file which is trained on my data?

Thank you for your help

**Comment by suryan-s** [comment]
> Hello
> 
> I have a custom trained pt file of yolov8 and when I create an engine file using your codebase, it defaults to the coco dataset classes. How do I export and run an engine file which is trained on my data?
> 
> Thank you for your help

Same query here!!
