### ISSUE TITLE
Output at index 0 has incorrect length Aborted (core dumped)

### ISSUE THREAD

**Issue by belalhmedan90** [cyrusbehr/YOLOv8-TensorRT-CPP#47]
Hi, I'm trying to run this repo using [FastSAM](https://github.com/CASIA-IVA-Lab/FastSAM?tab=readme-ov-file#model-checkpoints), I converted it using your script: 

```sh
python3 pytorch2onnx.py --pt_path ../../models/FastSAM-x.pt
```
and tried to run inference on this image:

![](https://content.parcelsolutions.net/9852df2d-bd78-4745-afcd-0b9bbe945b7b/content-hub/person%20stacking%20boxes%20onto%20a%20pallet.jpg)

But when I tried to do the detection, I got an error:
```sh
$ CUDA_MODULE_LOADING=LAZY ./detect_object_image --model ../../models/FastSAM-x.onnx --input ../../imgs_tst/boxes.jpg 
Searching for engine file with name: FastSAM-x.engine.NVIDIAGeForceRTX2070Super.fp16.1.1
Engine found, not regenerating...
terminate called after throwing an instance of 'std::logic_error'
  what():  Output at index 0 has incorrect length
Aborted (core dumped)
```
Can you please tell me how can I fix that please? thanks.

**Comment by cyrusbehr** [comment]
Hi there. My code hasn't been written to work with any arbitrary segmentation algorithm, it only works with yolov8 segmentation at the moment. You'll need to re-work the code a bit to make it work.
