### ISSUE TITLE
Error from number of outputs

### ISSUE THREAD

**Issue by rbgreenway** [cyrusbehr/YOLOv8-TensorRT-CPP#5]
Within your YoloV8::detectObjects function, your code checks to make sure the number of outputs == 1 for a detection model; however, when I take my custom yolov8-trained model for detection, it has 3 outputs...thus it thinks its a segmentation model and errors out.

Here's the command I use to train my custom model:

`yolo task=detect mode=train model=yolov8m.pt data=custom.yaml plots=True epochs=200 imgsz=640,480`

Once trained, I use your pytorch2onnx.py script to convert it to an onnx file.

This all seems odd to me since if I take one of the yolov8 provided models, e.g. yolov8m.pt, and convert it using your script, it only shows 1 output and runs fine.

Not sure what's going on.  Any ideas??

Thanks!

**Comment by rbgreenway** [comment]
Looks like it was a error in the way I converted the model to onnx.  I think I've fixed it.  
Sorry!

Thanks for this repo!

**Comment by cyrusbehr** [comment]
@rbgreenway can you expand more on what changes you made to the conversion script that fixed this problem, as to help people in the future if they have the same problem.

**Comment by rbgreenway** [comment]
@cyrusbehr I somehow converted it from a pt, or downloaded it from somewhere...I can't seem to recreate!  However, i did find a similar yolov8 onnx file with 4 outputs.  You can download from 
https://github.com/kn1ghtf1re/yolov8-deepstream-6-1

Here's an image of output of the network taken from Netron.  As you can see, there are 4 outputs.  
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/2991932/314a8573-bf6b-4153-b6e8-cd4cdbfaf6a4)

Not sure it's important now, but I'm very curious how they took the native .pt file from the results of training a yolov8 network, and converted it to such an onnx file with multiple outputs.  This looks like the "old style" outputs of yolo.

**Comment by rbgreenway** [comment]
@cyrusbehr 
Figured it out.  
The conversion tool provided at:
[(https://github.com/marcoslucianops/DeepStream-Yolo/blob/master/utils/export_yoloV8.py)]
creates multiple outputs that is compatible with his popular Deepstream plugin.
The ultralytics model.export function collapses that into a single output, which is the format that you use in your TensorRT interface.  

I now know how to use both approaches. Thanks!

**Comment by cyrusbehr** [comment]
I'm not certain, but it's possible you exported to onnx as end2end, which means that the model contains bbox decoding and nms (whereas my implementation does this using C++ code external to the model).

**Comment by rbgreenway** [comment]
I believe the "classic" yolo (i.e. Yolo 2/3/4) output is scores, classes, and boxes...like this:

![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/2991932/a5286a56-4cbf-419f-895f-0b2afecf1c1b)

For integration with DeepStream, the popular plugin linked in my previous comment decodes the bounding boxes outside of the model, and is compatible with most, if not all, the yolo variants, including yolov8.  Also in that repo, is a pytorch-to-onnx conversion script that creates an onnx file compatible with the Deepstream plugin...but not compatible with your TensorRT code.  However, I am now putting your code into a new Deepstream plugin mainly because it gives me better control over some of the special things I want to do with an image before inference.
