### ISSUE TITLE
A word of caution on this implimentation and broader yolo constructs.

### ISSUE THREAD

**Issue by rlewkowicz** [cyrusbehr/YOLOv8-TensorRT-CPP#51]
I'm here as are many others I'm sure because you used ultralytics and now you want tensorrt speed with c++ without dealing with onnx frameworks etc. 

Just a word of caution to passerbys, this implementation is kinda half baked.  For better or worse ultralytics obstructs a lot of concepts and handles so much for you sometimes you might not (I sure didn't) understand what really goes into these models and their nuanced differences. My understanding was, and to some extent still is if I do x, I get y but I don't actually understand all the underlying concepts. 

For example he says use his export script. Well no one tells you, and there are no errors if you dont use the same imgsz and then you're wondering why things are just... off. 

https://docs.ultralytics.com/modes/export/

Overall, I'm starting to wonder if ultralytics is generally not so hot. Its an awesome toolchain for beginners (me), but as you try to implement in other languages you start to realize you don't actually know what you're doing. 

https://docs.opencv.org/4.x/da/d9d/tutorial_dnn_yolo.html

This actually helped me just kind of bring into scope the concept of yolo models. Mind you this does not work with tensorRT, just a spot to explore other toolchains if you're here and finding walls. 

edit: Yeah, even after trying a ton of stuff, this just feels WILDLY under accurate and I'm just not well versed enough quite yet to know where I'm losing it.

**Comment by cyrusbehr** [comment]
Hey thanks for the feedback. 
This implementation was written as mainly a hobby project, and is only advised to be used as a starting point. Unfortunately I didn’t have the time to make it an infallible or highly robust implementation. 

That being said, if you have the energy, it would be appreciated if you could contribute to the project based on your learnings. I will give you credit in the readme as a project contributor.
