### ISSUE TITLE
Cannot detect object on Jetson AGX Orin

### ISSUE THREAD

**Issue by alfanrizaldy** [cyrusbehr/YOLOv8-TensorRT-CPP#6]
Hi, thank you for the amazing repository
I want to ask, i have followed your guide, but the result can't be detect object (no bounding boxes in any objects)
Here i use Jetson AGX Orin
Any help will be appreciated

**Comment by alfanrizaldy** [comment]
Above error happened in yolov8m, but when i use yolov8s, it run successfully
What caused that condition? I'm confuse how this can be happen

**Comment by cyrusbehr** [comment]
Hi @alfanrizaldy 
Can you try running the yolov8m model on x86 device with gpu and tell me if you still encounter this problem. Trying to understand if the issue is with the model you are using, or the platform you are running on.

**Comment by alfanrizaldy** [comment]
Ok, if I've already hands a x86 device to test the model i will inform here

**Comment by mouhannadali** [comment]
Hi @alfanrizaldy how did u manage the different TensorRT version in Jetson AGX Orin?

**Comment by ltetrel** [comment]
@alfanrizaldy you may want to look here: https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/issues/22
It is working on my side with a Jetson-TX2 which has an older hardware compare to yours.

**Comment by HXB-1997** [comment]
@cyrusbehr Is there any branch about deploying on Jetson AGX Xavier?

**Comment by cyrusbehr** [comment]
Please try out the branch I've linked there and see if it works for Jetson AGX Xavier.
