### ISSUE TITLE
How do I call the runInference when the engine need multi inputs?

### ISSUE THREAD

**Issue by anzisheng** [cyrusbehr/YOLOv8-TensorRT-CPP#62]
I found your example network only need one input, But I want handle multi inputs for the engine file . How do I call the runInference when the engine need multi inputs? 
                                                                               Thanks!

**Comment by cyrusbehr** [comment]
Hi there.
Please see the following.

[Docs](https://github.com/cyrusbehr/tensorrt-cpp-api/blob/6844785284e72c7cd92805c422ac6a0dab389039/src/engine.h#L88-L91) for the `runInference` method.

[Example](https://github.com/cyrusbehr/tensorrt-cpp-api/blob/6844785284e72c7cd92805c422ac6a0dab389039/src/main.cpp#L101) of how you would pass multiple inputs.
