### ISSUE TITLE
can't detetct the video

### ISSUE THREAD

**Issue by jcluo1994** [cyrusbehr/YOLOv8-TensorRT-CPP#65]
hello,i got some bug here,it works good on images,but it not work on video,here is the error:
Original video resolution: (0x0)
New video resolution: (0x0)
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unable to open video capture with input '/home/disk/workspace/tensorRT/tensorrt-master/test_t.mp4'
Aborted (core dumped)

btw:the format of video is correct.

**Comment by cyrusbehr** [comment]
Great, thanks for the update.

**Comment by zhuyuhang4** [comment]
> i have resolved my question by recompliing the opencv with ffmpeg.thanks again.

I have the same problem, how did you compile it?
