### ISSUE TITLE
How to do tracking mode?

### ISSUE THREAD

**Issue by nguyenlam185** [cyrusbehr/YOLOv8-TensorRT-CPP#7]
Good day @cyrusbehr ,
This is not an issue but a question of mine. I have tried your project, and it actually has saved me a lot of time. 
I am able to get the segmentation info, but now I need to get YoloV8 to work with tracking mode. Could you please tell me how to achieve that?

Thank you so much for your project, and also your time to answer this question

**Comment by cyrusbehr** [comment]
Hi @nguyenlam185 
I have not yet written an implementation for tracking.

If you can provide me with a sample code or resource which explains how to decode / interpret the output of the tracking model, I can implement it with TensorRT.

**Comment by cyrusbehr** [comment]
I would suggest you look at these repos for tracking algorithms in C++. 
- https://github.com/viplix3/BoTSORT-cpp
- https://github.com/Vertical-Beach/ByteTrack-cpp

**Comment by cyrusbehr** [comment]
What is the issue exactly? You should use YOLOv8 for detection of the objects, and then the byte track algorithm for the tracking portion. If you see the official ultralytics documentation, they also rely on these trackers I've linked above: 
![image](https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/assets/17056751/8d86831a-82bd-4190-af14-451f440c068f)


I'm not sure YOLOv8 actually has built in tracking.
