### ISSUE TITLE
Support for setting class names via public method

### ISSUE THREAD

**Issue by z3lx** [cyrusbehr/YOLOv8-TensorRT-CPP#8]
Currently, the library lacks support for setting custom class names externally without modifying the source code and recompiling it. I suggest adding a method that allows users to set custom class names programmatically (or through arguments in the cli). I am willing to contribute to the project by creating a pr.

**Comment by cyrusbehr** [comment]
Hi @z3lx 
Yes this is a good idea. We can have a default set of classes, but if the user provides the classes via command line, those are instead used. 
Please open a PR.

**Comment by z3lx** [comment]
Will start working on the changes asap 👍

**Comment by z3lx** [comment]
Hey @cyrusbehr, I wanted to let you know that I've just opened a pull request that introduces the features mentioned previously to the repository. I'd appreciate it if you could take some time to review the changes and provide your feedback. 

### Brief summary of the modifications
- Created a configuration struct: I've added a configuration struct to streamline the construction of the YoloV8 class. This struct comes with default values for each option, making it easy to override them as needed and pass the configuration into the constructor. 
- Improved argument parsing logic: I've completely rewritten the logic for parsing arguments in the executable. Now, every option can be set through the CLI. 

### Some observations
There are a few things I'd like to point out that could be addressed in future commits. 
- The logic and helper methods for parsing arguments can be separated into a separate script to avoid redundant code. However, I'm not too familiar with CMake, and I'm unsure about how to properly configuring these extra files. 
- The detect_object_image and detect_object_video executables can be merged into a singular program as they're both very similar in structure and functionality.

**Comment by cyrusbehr** [comment]
Thanks for the fast turn around @z3lx 
I will review the PR this weekend.

**Comment by cyrusbehr** [comment]
Merged. Thank you for your contribution.

**Comment by cyrusbehr** [comment]
I did some reorganizing: https://github.com/cyrusbehr/YOLOv8-TensorRT-CPP/commit/46bc9b2e021788c2f534c150f0a55ae37a163d56

Thanks your code works well!

**Comment by cyrusbehr** [comment]
@all-contributors please add @z3lx  for improving cli argument parser

**Comment by cyrusbehr** [comment]
@all-contributors please add @z3lx  for code
